# This code was generated by GitHub Copilot (qwen2.5-coder:7b & GPT-4o).
# It has not been manually reviewed, tested, or modified.
# Use at your own risk.

import os
import sys
import time
import argparse  # argparseを追加
from utils.api import get_mods_by_version, get_latest_mod_download_url, get_all_mod_download_urls
from utils.downloader import download_mod

def process_mods(mod_slugs, game_version, download_directory=None, list_urls=False):
    """
    Process mods by either listing URLs or downloading them.

    Args:
        mod_slugs (list): List of mod slugs.
        game_version (str): The game version to fetch mods for.
        download_directory (str): Directory to download mods to (if applicable).
        list_urls (bool): Whether to list URLs instead of downloading.

    Returns:
        None
    """
    mediafire_warnings = []

    for i, slug in enumerate(mod_slugs):
        if i > 0 and i % 20 == 0:
            print("Rate limit reached. Waiting for 1 minute...")
            time.sleep(60)

        if not list_urls:
            print(f"Fetching all download URLs for mod: {slug}")
        try:
            mod_urls = get_all_mod_download_urls(slug, game_version)
        except ValueError as e:
            print(f"\033[91mError: {e}\033[0m")
            continue

        if mod_urls:
            for mod_url in mod_urls:
                if list_urls:
                    print(mod_url)
                elif "mediafire.com" in mod_url:
                    mediafire_warnings.append(f"{slug}: {mod_url}")
                else:
                    print(f"Downloading mod from: {mod_url}")
                    download_mod(mod_url, download_directory)
                time.sleep(3)  # Wait 3 seconds between downloads
        else:
            print(f"\033[93mWarning: Download URLs not found for mod: {slug}\033[0m")

    if mediafire_warnings:
        print("\n\033[93mMediaFire links detected. These may require manual download:\033[0m")
        for warning in mediafire_warnings:
            print(f"\033[93m{warning}\033[0m")

def main():
    parser = argparse.ArgumentParser(
        description="MCArchive Downloader",
        epilog="Example usage: python src/main.py --download b1.7_01 ./mods"
    )
    parser.add_argument("--download", action="store_true", help="Download mods for the specified game version and save them to the specified directory.")
    parser.add_argument("--url", action="store_true", help="List all mod URLs for the specified game version.")
    parser.add_argument("game_version", type=str, help="The game version to fetch mods for (e.g., b1.7_01).")
    parser.add_argument("download_directory", type=str, nargs="?", help="The directory to download mods to (required for --download).")

    args = parser.parse_args()

    if args.download and not args.download_directory:
        print("Error: --download requires a download directory to be specified.")
        sys.exit(1)

    game_version = args.game_version

    print(f"Fetching mods for version: {game_version}")
    try:
        mod_slugs = get_mods_by_version(game_version)
    except ValueError as e:
        print(f"\033[91mError: {e}\033[0m")
        sys.exit(1)

    print(f"Mod slugs fetched: {mod_slugs}")

    if args.url:
        print("Listing all mod URLs:")
        process_mods(mod_slugs, game_version, list_urls=True)
        return

    if args.download:
        download_directory = args.download_directory

        if not os.path.exists(download_directory):
            os.makedirs(download_directory)

        process_mods(mod_slugs, game_version, download_directory=download_directory)

        print("Download completed.")

if __name__ == "__main__":
    main()